config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'users#home'
  devise_for :users
  resources :posts do
    resources :likes
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord

  has_many :likes, dependent: :destroy
  has_attached_file :image, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/


  belongs_to :user

end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :likes, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def after_sign_in_path_for(_resource)
    posts_path
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_post
  before_action :find_like, only: [:destroy]
  
  def create
    if already_liked?
      flash[:notice] = "You can't like more than once"
    else
      @post.likes.create(user_id: current_user.id)
   end
     redirect_to posts_url
  end

  def destroy
    if !(already_liked?)
      flash[:notice] = "Cannot unlike"
    else
      @like.destroy
    end
    redirect_to posts_url
  end

  def find_like
    @like = @post.likes.find(params[:id])
 end

  private
  def find_post
    @post = Post.find(params[:post_id])
  end

  def already_liked?
  Like.where(user_id: current_user.id, post_id:
  params[:post_id]).exists?
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    @post.user = current_user
    @post.save
    redirect_to posts_url
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to posts_url
    else
      render :edit
    end
  end

  def index
    @posts = Post.order('Created_at DESC').all
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_url
  end

  private

  def post_params
    params.require(:post).permit(:message, :image)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Acebook</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://kit.fontawesome.com/4bfa6e9b47.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render "shared/header" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for post, html: { multipart: true } do |form| %>
  <%= form.label :message, class: "label" %>
  <%= form.text_area :message, class: "input" %>
  <br>
  <%= form.label :image, class: "label" %>
  <%= form.file_field :image %>
  <br>
  <br>
  <%= form.submit "Submit", class: "button is-success" %>

<% end %>

app/views/posts/edit.html.erb
<div class="columns is centered mt-6">
  <div class="column is-one-third">
  <h1 class="is-size-3 has-text-weight-bold mb-3"> Edit post</h1>
    <%= render "form", post: @post%>
  </div>
</div>

app/views/posts/index.html.erb
<div class="columns mt-6 is-centered table-container">
  <div class="column is-half">
    <% @posts.each do |post| %>
    <div class="card">
      <header class="card-header">
        <% time_posted = post.created_at %>
        <p class="card-header-title"><%= post.user.email.split('@')[0].capitalize %></p>
        <p class="pr-2"><%= time_posted.strftime("%m/%d/%Y %I:%M%p") %></p>
      </header>
      <div class="card-content">
        <div class="content">
          <p class="form"><%= post.message %></p>
          <% unless post.image.url == '/images/original/missing.png'%>
          <%= image_tag post.image.url(:medium)%>
          <% end %>
        </div>
      </div>
      <% if post.user == current_user %>
      <div class="card-footer">
        <span class="icon">
          <i class="far fa-thumbs-up ml-4"></i> 
        </span>
        <p class="ml-2"><%= post.likes.count %></p>
        <% if Time.now - post.created_at < 10.minutes%>
        <%= link_to 'Edit', edit_post_path(post), class: "card-footer-item" %>
        <% end %>
        <%= link_to 'Destroy', post, method: :delete, data: { confirm: "Are you sure?" }, class: "card-footer-item mr-6"%>
      </div>
      <% end %>
        <% if current_user != post.user%>
          <div class="card-footer">
            <% pre_like = post.likes.find { |like| like.user_id == current_user.id} %>
            <% if pre_like %>
              <%= link_to post_like_path(post, pre_like), method: :delete do %>
                <i class="far fa-thumbs-up ml-3"></i>
              <%end%>
            <% else %>
              <%= link_to post_likes_path(post), method: :post do %>
                <i class="far fa-thumbs-up ml-3"></i>
              <% end %>
            <% end %>
          <p class="ml-2"><%= post.likes.count %></p>
          </div>
        <% end %>
    </div>
    <br>
    <% end %>
    <%= link_to 'New post', new_post_path, class: "button is-success" %>
  </div>
</div>
<br>

app/views/posts/new.html.erb
<div class="columns is centered mt-6">
  <div class="column is-one-third">
    <h1 class="is-size-3 has-text-weight-bold mb-2"> New Post</h1>
    <%= render "form", post: @post%>
  </div>
</div>

app/views/shared/_header.html.erb
<section class="hero has-background-link-dark is-small">
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
            <span class="navbar-item">
              <h1 class="title has-text-primary-light">Acebook</h1>
            </span>
          <span class="navbar-burger burger" data-target="navbarMenuHeroB">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroB" class="navbar-menu">
          <div class="navbar-end">
              <% if current_user %>
              <span class="navbar-item">
                <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "button is-success" %>
              </span>
                <% unless current_page?('/posts')%>
                <span class="navbar-item">
                  <%= link_to 'View posts', posts_path, class: "button is-success" %>
                </span>
                <% end %>
              <% else %>
              <span class="navbar-item">
                <%= link_to 'Sign in', new_user_session_path, class: "button is-success" %>
              </span>
              <span class="navbar-item">
                <%= link_to 'Sign up', new_user_registration_path, class: "button is-success" %>
              </span>
              <% end %>
          </div>
        </div>
      </div>
    </nav>
  </div>
</section>
<script type="text/javascript">
  (function() {
    var burger = document.querySelector('.burger');
    var nav = document.querySelector('#'+burger.dataset.target);

    burger.addEventListener('click', function(){
      burger.classList.toggle('is-active');
      nav.classList.toggle('is-active');
    });
  })();
</script>

app/views/users/home.html.erb
<style>
body {
  /* Location of the image */
  background-image: url('https://images3.alphacoders.com/106/1069102.jpg');
  
  /* Background image is centered vertically and horizontally at all times */
  background-position: center center;
  
  /* Background image doesn’t tile */
  background-repeat: no-repeat;
  
  /* Background image is fixed in the viewport so that it doesn’t move when
  the content’s height is greater than the image’s height */
  background-attachment: fixed;
  
  /* This is what makes the background image rescale based
  on the container’s size */
  background-size: cover;
  
  /* Set a background color that will be displayed
  while the background image is loading */
  background-color: #464646;
  }
</style>